# -*- coding: utf-8 -*-
"""SENSEX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RqvBFfijR517w2an1vR41luTkSet6_lq
"""

import yfinance as yf
import pandas as pd
import datetime

# Define the period for the last 6 months (180 days)
end_date = datetime.datetime.now()
start_date = end_date - datetime.timedelta(days=180)

# Define the BSE Sensex ticker symbol
sensex_ticker = '^BSESN'

# Fetch historical data for the Sensex
sensex_data = yf.download(sensex_ticker, start=start_date, end=end_date)

# Create a new DataFrame with the required columns
output_df = pd.DataFrame()

# Add the Date column
output_df['Date'] = sensex_data.index

# Add the Closing Price column
output_df['Closing Price'] = sensex_data['Adj Close']

# Calculate and add the Change in Price from the previous day
output_df['Price Change'] = sensex_data['Adj Close'].diff()

# Add the Volume column
output_df['Volume'] = sensex_data['Volume']

# Calculate and add the Change in Volume from the previous day
output_df['Volume Change'] = sensex_data['Volume'].diff()

# Calculate and add the High Price - Low Price column
output_df['High - Low'] = sensex_data['High'] - sensex_data['Low']

# Save the output DataFrame to an Excel file
output_file = 'sensex_data_6_months.xlsx'
output_df.to_excel(output_file, index=False)

print(f"Data successfully written to {output_file}")